(defvar *color-rule*)
(setf *color-rule*
      '(;;("MSC" "red")
	;;("media" "red")
	("SDP" "red")
	("sdp" "red")
	;;("voice" "red")
	;;("Voice" "red")
	("RTP" "red")
	("DTMF" "red")
	;;("Media" "red")
	("Mi " "red")
	;;("BGCF" "red")
	("TrGW" "red")
	;;("MSRP " "red")
	;;("MRFC" "red")
	;;("MRB " "red")
	("megaco" "red")
	("H.248" "red")
	("I2" "red")
	("Izi" "red")
	("Mm " "red")
	("Mx" "red")
	("payload" "red")
	("m=" "red")
	("b=" "red")
	("a=" "red")
	("rtpmap" "red")
	("bandwidth" "red")
	("encoding" "red")
	("AMR" "red")
	;;("MGW" "red")
	))

	
;;("" "red")



